export const splashBackground = require('../images2/Splash.png')
export const backIcon = require('../images2/backIcon.png')
export const userIcon = require('../images2/userIcon.png')
export const homeIcon = require('../images2/homeIcon.png')
export const chatIcon = require('../images2/chatIcon.png')
export const cartIcon = require('../images2/cartIcon.png')
export const bottomBar = require('../images2/BottomBar.png')
export const bottomButton = require('../images2/bottomButton.png')
export const notificationIcon = require('../images2/notification.png')
export const searchIcon = require('../images2/search.png')
export const engine1 = require('../images2/engine1.png')
export const engine2 = require('../images2/engine2.png')
export const vlorIcon = require('../images2/vlor.png')
export const seetIcon = require('../images2/seet.png')
export const breakIcon = require('../images2/break.png')
export const speakerIcon = require('../images2/speaker.png')
export const lightIcon = require('../images2/light.png')
export const tireIcon = require('../images2/tire.png')
export const emojiIcon = require('../images2/emoji.png')
export const attechmentIcon = require('../images2/attechmentIcon.png')
export const cameraIcon = require('../images2/cameraIcon.png')
export const dashIcon = require('../images2/dashIcon.png')
export const settingsIcon = require('../images2/settingsIcon.png')
export const homeIconprofile = require('../images2/homeIconprofile.png')
export const userIconProfile = require('../images2/userIconProfile.png')
export const garageIcon = require('../images2/garageIcon.png')
export const pendingIcon = require('../images2/pending.png')
export const deliveredIcon = require('../images2/delivered.png')
export const reviewedIcon = require('../images2/reviewed.png')
export const detailsIcon = require('../images2/details.png')
export const couponIcon = require('../images2/coupon.png')
export const wishlistIocn = require('../images2/wishlist.png')
export const binIcon = require('../images2/bin.png')
export const pinIcon = require('../images2/pin.png')
export const couponAvailable = require('../images2/CouponAvailable.png')
export const couponUsed = require('../images2/CouponUsed.png')
export const heartIconWishlist = require('../images2/heartIconWishlist.png')
export const binIcon2 = require('../images2/binIcon2.png')
export const cardIcon = require('../images2/cardIcon.png')
export const codIcon = require('../images2/codIcon.png')
export const orderPlacedIcon = require('../images2/orderPlacedIcon.png')
export const carIcon = require('../images2/carIcon.png')
export const bikeIcon = require('../images2/bikeIcon.png')
export const vanIcon = require('../images2/vanIcon.png')
export const lightIcon2 = require('../images2/lightIcon.png')
export const editIcon = require('../images2/editIcon.png')
export const pointsIcon = require('../images2/pointsIcon.png')
export const supportIcon = require('../images2/supportIcon.png')
export const faqIcon = require('../images2/faqIcon.png')
export const logoutIcon = require('../images2/logoutIcon.png')
export const pointsIconStation = require('../images2/pointsIconStation.png')
export const privacyIcon = require('../images2/privacyIcon.png')
export const returnPolicyIcon = require('../images2/returnPolicyIcon.png')
export const allOrdersIcon = require('../images2/allOrdersIcon.png')
export const qrequested = require('../images2/qrequested.png')
export const downTick = require('../images2/downTick.png')
export const upTick = require('../images2/upTick.png')
export const uploadIcon = require('../images2/uploadIcon.png')
export const userSignUpStation = require('../images2/userSignUpStation.png')
export const pinSignUpIcon = require('../images2/pinSignUpIcon.png')
export const signUpGarageIcon = require('../images2/signUpGarageIcon.png')
export const forwardIcon = require('../images2/forwardIcon.png')
export const moreIcon = require('../images2/moreIcon.png')
export const plusIcon = require('../images2/plusIcon.png')
export const minusIcon = require('../images2/minusIcon.png')
export const Dashlk = require('../images2/Dash.lk.png')
export const passIcon = require('../images2/passIcon.png')
export const bottomPlusIcon = require('../images2/bottomPlusIcon.png')
export const calenderIcon = require('../images2/calenderIcon.png')
export const ratingIcon = require('../images2/ratingIcon.png')















